import React from 'react';

const Privacy = () => {
    return (
        <div className='container mx-auto mt-16 '>
            <h1 className='text-5xl font-semibold my-8'>Privacy Policy</h1>
            <div className='text-xl leading-9'>
                <p>At Stratuscent Inc. (“Stratuscent”, “we”, “us” or “our”) we take your privacy and the security of your information very seriously.

                    This Privacy Policy (“Policy”) covers Stratuscent owned and operated websites, including www.getnoze.com (“Site” or “Sites”) and any services offered by Stratuscent, including our provision of air quality monitoring devices, and any of our applications (“applications”, “apps”, “App”), and associated services (collectively, the “Services”). This Privacy Policy is incorporated into, and is part of, our Terms of Use (available at https://www.getnoze.com/terms) which govern your access to the Site and your use of the Site and/or Services. Unless otherwise defined herein, capitalized terms shall have the meaning assigned to such terms in the Terms of Use.

                    If you have any questions regarding this Policy please contact us at help@getnoze.com.

                    The Policy describes the types of information we gather from people visiting our Site and from individual users (“you” or “users”) interacting with the Services, and how we use, transfer, and secure such information. By accessing any of our Site or using any of the Services, you agree to be bound by this Policy. This Policy does not govern information we receive from third parties. If you do not agree to the terms of this Policy, please do not use the Site, or any of our Services. Each time you use any Sites, or Services, the current version of this Privacy Policy will apply. Accordingly, when you use any Site or Services, you should check the date of this Policy (which appears at the bottom) and review any changes since you last reviewed the Policy</p>
                <h1 className='font-bold'>1. Types of Information We Collect</h1>
                <p>Stratuscent may collect two types of information from users of our Sites and Services: “Personal Information” which is information that you provide that can be used to identify you (such as name or e-mail address, etc.) and “Aggregate Information” which is information that cannot be used to identify you (such as frequency of visits to the Site, browser type, etc.)</p>
                <h1 className='font-bold'>1.1. Personal Information Collected.</h1>
                <p>1.1.1. Stratuscent collects Personal Information you voluntarily provide to us when you use our Sites and Services, including our apps. For example, you may provide us with your email address, first name and last name, shipping address, or other Personal Information.
                </p>
                <p>1.1.2. Further, we may collect Personal Information through your voluntary use of any Stratuscent provided Apps. Where such data constitutes Personal Information we will treat it as such. Certain options within Stratuscent provided Apps may provide you options as to which Personal Information you wish to provide, and the frequency or timing or when you provide Personal Information to Stratuscent. To stop the collection of any data, including Personal Information, from any Stratuscent provided Apps, please uninstall the App using your device provided procedures.</p>
                <p>1.1.3. We do not control your use of our Sites and Services to share Personal Information with others. If you chose to share information publicly through our Site or Services please understand that we cannot control the actions of third parties who could collect this information.</p>
                <h1 className='font-bold'>1.2. Collection of Personal Information by Third Parties.</h1>
                <p>1.2.1. Some links on our Site may redirect you to third party websites and services that We do not operate. The privacy practices of these websites and services will be governed by their own policies. We make no representation or warranty as to the privacy policies of any third parties, including the providers of third party applications. If you are submitting information to any such third party through our Site or Services, you should review and understand that party’s applicable policies, including their privacy policy, before providing your information to the third party.</p>
                <p>1.2.2. For example, it is possible that your payment information, such as credit card or debit card information, may be collected and stored by third party payment vendors, should you choose to provide such a payment method to a third party through your use of the Site or Services.</p>
                <p>1.2.3. We do not currently collect financial information, such as your payment method (valid credit card number, type, expiration date or other financial information); that information is collected and stored by our third party payment processing company (the “Payment Processor”), and use and storage of that information is governed by the Payment Processor’s applicable terms of service and privacy policy. We may from time to time request and receive certain information from our Payment Processor or from you directly for purposes of completing transactions you have initiated through the Services, protecting against or identifying possible fraudulent transactions, and otherwise as needed to manage our business. In no cases will such requested information allow for a financial transaction to be initiated.</p>
                <h1 className='font-bold'>1.3. Aggregate Information Collected.</h1>
                <p>1.3.1. Aggregate Information is information that does not identify you. Aggregate Information may be collected when you visit our Site or interact with our Services independent of any information you voluntarily enter. We may collect, use, store, and transfer Aggregate Information without restriction. We may further de-identify Personal Information such that it may no longer be reasonably used to identify you, such that it becomes Aggregate Information.</p>
                <p>1.3.2. For example, when you visit our Site, some information is automatically collected. Such information could include your operating system, the site from which you linked to us (“referring page”), the name of the website you chose to visit immediately after ours (called the “exit page”), information about other websites you have recently visited, browser (software used to browse the internet) type and language, device identifier numbers, your site activity, and the time and date of your visit. Although we do our best to honor the privacy preferences of our visitors, we are not able to respond to Do Not Track signals from your browser at this time.</p>
                <p>1.3.3. Additionally, from time to time, we may allow you to post reviews, comments, photos, or similar materials on the Site (collectively, “Reviews”). We welcome your comments regarding our products and services, including our Site. However, any Reviews you submit to us must not harass, slander, malign, libel, defame, threaten, or otherwise violate any rights of any third-parties and must not include any profanity, obscene, indecent, pornographic, defamatory or unlawful material.</p>
                <p>1.3.4. Through the use of Stratuscent provided Apps you may also choose to provide other information that does not identify you such as data regarding brushing behavior and timing.</p>
                <p>1.3.5. By posting a Review on the Site, you hereby grant us an unrestricted, assignable, sublicensable, perpetual royalty-free, fully paid up license throughout the world to reproduce, distribute, publicly display, transmit, communicate to the public, publicly perform on a through-to-the-audience basis, create derivative works from, and otherwise use and exploit (collectively, “Use”) all Reviews you post to the Site, for any purpose, including promoting and marketing us and any products or services we choose to offer. You further grant us a royalty-free license to Use the name, image, and likeness of any person identifiable in any Review you post to the Site. By posting a Review, you waive any and all rights of publicity, privacy or any other rights of a similar nature, in addition to any moral rights you may have in your Review. Except for materials provided to you by us through the Site, you represent, warrant, and covenant that
                    <br />
                    (i) you either are the sole and exclusive owner of Reviews that you post to the Site, or you have all rights, licenses, consents, and releases that are necessary to grant to us the rights in your Reviews as contemplated under our Terms of Use and this Policy, and
                    (ii) the Reviews you post to the Site do not
                    <br />
                    (A) infringe, misappropriate or violate the rights of any party or entity, including a third-party’s patent, copyright, trademark, trade secret, moral rights, rights of publicity, rights of privacy or other intellectual property or proprietary rights,
                    <br />
                    (B) constitute or result in defamation, libel, slander, or the violation of any applicable law or regulation (including, without limitation, restrictions on obscenity, child pornography, wiretap laws or other similar restrictions on nonconsensual recording, or otherwise), or
                    <br />
                    (C) require we to obtain any licenses from or make any payments in any amounts to any third-party throughout the world.</p>
                <p><span className='font-bold'>1.4. No Objectionable Content.</span> You agree not to submit Reviews that: (i) are or could be interpreted to be infringing, defamatory, libelous, inaccurate, unlawful, harmful, threatening, abusive, harassing, vulgar, offensive, obscene, pornographic, objectionable, hateful, or promotes discrimination, bigotry, racism, or hatred, as determined by us in its sole discretion; or (ii) introduce viruses, time-bombs, worms, cancel bots, Trojan Horses and/or other harmful or malicious code.</p>
                <p><span className='font-bold'>1.5. Monitoring.</span> We have no obligation to monitor this Site or any portion thereof. However, we reserve the right to review any Reviews and remove, delete, redact or otherwise modify such Reviews, in our sole discretion, at any time and from time to time, without notice or further obligation to you. We have no obligation to display or post any Reviews. Subject to this Policy, we reserve the right to disclose, at any time and from time to time, any information or posted content that it deems necessary or appropriate, including without limitation to satisfy any applicable law, regulation, contractual obligation, legal, dispute process, or governmental request.</p>
                <p><span className='font-bold'>1.6. Use of “Cookies”.</span>  Cookies are alphanumeric identifiers that we transfer to your computer’s hard drive through your web browser to help us identify you when you come to our website. You have choices with respect to cookies. By modifying your browser preferences, you have the choice to accept all cookies, to be notified when a cookie is set, or to reject all cookies. If you choose to reject all cookies you may be unable to use those aspects of our Sites which require registration in order to participate. You can learn more about cookies and how they work at www.allaboutcookies.org. You can always disable cookies through your browser settings. Doing so, however, may disable certain features on our websites.</p>
                <h1 className='font-bold'>1.7. Analytics.</h1>
                <p>1.7.1. We may use third parties, such as analytics providers, including Google Analytics to analyze traffic to this web site. Google Analytics does not create individual profiles for visitors and only collects aggregate data. To disable Google Analytics, please download the browser add-on for the deactivation of Google Analytics provided by Google at http://tools.google.com/dlpage/gaoptout?hl=en. To learn more about privacy and Google Analytics, please consult the Google Analytics overview provided by Google at http://www.google.com/intl/en/analytics/privacyoverview.html. You may find additional information about Google Analytics at http://www.google.com/policies/privacy/partners/. You have the option to opt out of Google’s use of cookies by changing your settings through Google Ad Settings, visiting the Google advertising opt-out page at http://www.google.com/policies/technologies/ads/.</p>
                <p>1.7.2. We may also use cookies, pixels, beacons, or other web tracking technologies to track the amount of time spent on our Sites or social media and whether or not certain content, such as a video was viewed. We may work with a trusted third party to collect and process this information for us, based on our instructions and in compliance with this Privacy Policy.</p>
                <h1 className='font-bold'>1.8. Interest-Based Advertising.</h1>
                <p>p1.8.1. We may also participate in interest-based advertising using similar technology. This means that you may see advertising on our Sites tailored to how you browse or shop, or you may see advertising for We and its properties on other websites based on your browsing behavior across websites. Some websites where we may advertise belong to ad networks that use your web browsing history to choose which ads to display on their network websites; these ads include advertising for We and its Sites. Other websites where you see our ads, such as Facebook, may use interest preferences that you have chosen on those sites, as well as registration and other information about you, to choose which ads to display to you. Some internet browsers, websites such as Facebook and mobile devices offer opt-outs for interest-based advertising. Please refer to the website that you are visiting, your browser and/or your device settings for additional information.</p>
                <p>1.8.2. You can opt-out of receiving interest-based ads from third parties who are members of the Network Advertising Initiative (NAI) or who follow the Digital Advertising Alliance’s Self-Regulatory Principles for Online Behavioral Advertising by visiting the opt-out pages on the NAI website (http://www.networkadvertising.org/choices/) and DAA website (http://www.aboutads.info/choices/).</p>
                <h1 className='font-bold'>2. Sharing of Personal Information with Third Parties</h1>
                <p>2.1. We may transfer Personal Information to third parties for the purpose of providing the Services. We may disclose Personal Information to our appropriate affiliates, including third party service providers, to provide you with the Services. For example, we may transfer your Personal Information to third party service providers to (i) provide subscription based products or services (ii) communicate with you about your purchases or other offers. These third party service providers are not authorized to retain, share, store or use the Personal Information for any purposes other than to provide the services they have been hired to provide.</p>
                <p>2.2. We may also elect to transfer your Personal Information to third parties under special circumstances to:
                    <br />
                    (i) to comply with a legal requirement, judicial proceeding, court order, or legal process served on Us,
                    (ii) to investigate a possible crime, such as fraud or identity theft;
                    (iii) in connection with the sale, purchase, merger, reorganization, liquidation or dissolution of Stratuscent;
                    (iv) when we believe it is necessary to protect the rights, property, or safety of Stratuscent or other persons, or
                    (v) as otherwise required or permitted by law, including any contractual obligations of Stratuscent.</p>
                <p>2.3. Other Third Parties. We may also receive additional information about you to supplement the information we collect directly, such as demographic, contact, and statistical information, from third parties, such as business partners, marketers, data co-ops (into which companies contribute certain information about their customers (e.g., name and email address) in exchange for information from one another to enhance their customer lists and preferences), researchers, analysts, and other parties</p>
                <h1 className='font-bold'>3. Children and Privacy</h1>
                <p>We do not knowingly collect Personal Information from children in connection with the features of our Sites or Services. If we become aware that an individual under the age of 13 has provided personally identifiable information through our Sites or Services, we will immediately remove the individual’s personally identifiable information from our files.</p>
                <h1 className='font-bold'>4. Visitors That Reside Outside The United States</h1>
                <p>We provide these Sites and Services for the purpose of creating an enjoyable experience for our customers. The laws governing our collection and use of information may be different from the laws of your country. If you decide to use our Site or Services, or share your Personal Information with Us, you are agreeing to be governed by these laws, and you are expressly consenting to the transfer of your data to the United States.</p>
                <h1 className='font-bold'>5. How Does Stratuscent Protect My Information</h1>
                <p>5.1. Stratuscent takes the security of your Personal Information very seriously. We use reasonable administrative, physical, and technical safeguards to secure the Personal Information you share with us. Despite these safeguards and our additional efforts to secure your information, We cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third-parties will not be able to defeat our security, and improperly collect, access, steal, or modify your Personal Information.</p>
                <p>5.2. The security of your use of your account relies on your protection of your user name and password. You may not share your user name and password with anyone. If you believe that unauthorized access to your account has occurred please report it immediately at help@getnoze.com. You must promptly notify us if you become aware that any information provided by or submitted to your account has been lost, stolen, or used without permission. We will never ask you to send your password or other sensitive information to us in an email, though we may ask you to enter this type of information on a Stratuscent website.</p>
                <p>5.3. Any email or other communication purporting to be from one of our websites requesting your password or asking you to provide sensitive account information via email, should be treated as unauthorized and suspicious and should be reported to us immediately by emailing help@getnoze.com. If you believe someone else has obtained access to your password, please change it immediately by logging in to your account and selecting the provided option to change your password and report it immediately by emailing help@getnoze.com.</p>
                <h1 className='font-bold'>6. Will We Change This Privacy Policy?</h1>
                <p>Each time you use our Site or Services the current version of the Policy will apply. When you use our Site, you should check the date of this Policy (which appears at the bottom of the Policy) and review any changes since the last version. Our business changes frequently and this Policy is subject to change from time to time. Unless stated otherwise, our current Policy applies to all information that we have about you. We will not materially change our policies and practices to make them less protective of your privacy without the consent of affected customers.</p>
                <h1 className='font-bold'>7. How Do I contact Stratuscent?</h1>
                <p>To contact us with your questions or comments regarding this Policy or information collection and dissemination practices, please email us at help@getnoze.com.</p>
                <h1 className='font-bold'>8. Governing Law</h1>
                <p>This Policy is governed by the laws of the Province of Quebec, Canada without giving effect to any principles of conflict of law.</p>
                <p className='mt-5'>Last Updated: <span className='font-bold '> July 15, 2021</span></p>
            </div>
        </div>
    );
};

export default Privacy;