import React from 'react';

const Terms = () => {
    return (
        <div>
            <div className='container mx-auto mt-16 '>
                <h1 className='text-5xl font-semibold my-8'>Terms of Use</h1>
                <div className='text-xl leading-9'>
                    <p>Thank you for using Noze. Stratuscent Inc., a corporation organized under the laws of Canada (“Stratuscent”, “we”, “our”, “us” or the “Company”) welcomes you (the “User(s)” and “you”) to the Noze website located at getnoze.com (the “Website”), to your use of the Noze Device (“Noze” or the “Device”), and to the Noze mobile and online platforms (the “App”), through which you can access the services the Company offers through use of the Noze Device (“Services”). These Terms of Use together with the Privacy Policy (available at www.getnoze.com/privacy) form a legally binding contract between you and Stratuscent regarding your use of the Services.</p>
                    <br />
                    <p>PLEASE READ THE FOLLOWING TERMS OF USE CAREFULLY. BY CLICKING “I ACCEPT,” REGISTERING FOR AN ACCOUNT, DOWNLOADING A NOZE MOBILE APPLICATION, ACCESSING, BROWSING, OR OTHERWISE USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THE FOLLOWING TERMS OF USE, INCLUDING THE NOZE PRIVACY POLICY, ANY OTHER APPLICABLE TERMS PRESENTED TO YOU BY STRATUSCENT, AND ANY ADDITIONAL TERMS OR FUTURE MODIFICATIONS (COLLECTIVELY, THE “TERMS”). IF YOU DON’T AGREE TO THESE TERMS, DO NOT USE NOZE.</p>
                    <br />
                    <p>
                        If you are using Noze on behalf of an organization (such as your employer), you are agreeing to these Terms for that organization, and are indicating that you have the authority to bind that organization to these Terms. In that case, “you” and “your” will refer to that organization.</p>
                    <br />
                    <p>We may revise the Terms from time to time. If a revision is material, as determined solely by us, we will notify you (for example via email to the email address associated with your account). The most current version will always be posted on our Terms page. By continuing to use Noze after revisions become effective, you agree to be bound by the revised Terms. If you do not agree to the new Terms, please stop using Noze.</p>
                    <br />
                    <h1 className='font-bold'>1. ELIGIBILITY</h1>
                    <p>You represent and warrant that you are at least 13 years of age. If you are under age 13, you may not, under any circumstances or for any reason, use the Services. We may, in our sole discretion, refuse to offer the Services to any person or entity and change its eligibility criteria at any time. You are solely responsible for ensuring that these Terms of Use are in compliance with all laws, rules and regulations applicable to you and the right to access the Services is revoked where these Terms of Use or use of the Services is prohibited or to the extent offering, sale or provision of the Services conflicts with any applicable law, rule or regulation. Further, the Services are offered only for your use, and not for the use or benefit of any third party.</p>
                    <br />
                    <h1 className='font-bold'>2. YOUR INFORMATION AND RESPONSIBILITIES</h1>
                    <p>2.1. To use Noze, you’ll need to create an account, either via the Noze app or through your account with a third-party service such as Google or Facebook. In the latter case, your Noze account will be created using the information you provided to that service, such as your name and email address and other personal information that your privacy settings on that service permit us to access.
                    </p>
                    <p>2.2. You are responsible for safeguarding the password that you use to access Noze. You are solely responsible for the activity that occurs on your Account, and for keeping your Account password secure. You may never use another person’s user account or registration information for the Services without permission. You must notify us immediately of any change in your eligibility to use the Services (including any changes to or revocation of any licenses from state authorities), breach of security or unauthorized use of your Account. You should never publish, distribute or post login information for your Account. You shall have the ability to delete your Account, either directly or through a request made to one of our employees or affiliates.</p>
                    <p>2.3. By using Noze, you provide us with text, graphics, images and other information (“your content”). You retain full ownership of your content. Noze does not claim any ownership rights to your content. However, you are also solely responsible for your content. You indicate that you own or have the necessary rights to all of your content, and that use of your content does not infringe, misappropriate or violate a third party’s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.</p>
                    <br />
                    <h1 className='font-bold'>3. NOZE INTELLECTUAL PROPERTY RIGHTS</h1>
                    <p>3.1. Stratuscent and its licensors exclusively own Noze, including all associated intellectual property rights. You acknowledge that Noze is protected by copyright, trademark, and other laws of Canada and foreign countries. You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights or notices incorporated in or accompanying Noze.</p>
                    <p>3.2. Noze grants you a limited, non-exclusive, non-transferable license to view and display Noze solely in connection with your permitted use of Noze.</p>
                    <br />
                    <h1 className='font-bold'>   4. USE LICENSE</h1>
                    <p>Subject to these Terms of Use, we grant each user of the Services a worldwide, non-exclusive, non-sublicensable and non-transferable license to use (i.e., to download and display locally) Content solely for purposes of using the Services. Use, reproduction, modification, distribution or storage of any Content for other than purposes of using the Services is expressly prohibited without prior written permission from us. You shall not sell, license, rent, or otherwise use or exploit any Content for commercial use or in any way that violates any third party right.</p>
                    <br />
                    <p><span className='font-bold'>1.4. No Objectionable Content.</span> You agree not to submit Reviews that: (i) are or could be interpreted to be infringing, defamatory, libelous, inaccurate, unlawful, harmful, threatening, abusive, harassing, vulgar, offensive, obscene, pornographic, objectionable, hateful, or promotes discrimination, bigotry, racism, or hatred, as determined by us in its sole discretion; or (ii) introduce viruses, time-bombs, worms, cancel bots, Trojan Horses and/or other harmful or malicious code.</p>
                    <h1 className='font-bold'>5. CONTENT DEFINITION</h1>
                    <p>For purposes of these Terms of Use, the term “Content” includes, without limitation, information, data, text, photographs, videos, audio clips, written posts and comments, software, scripts, graphics, and interactive features generated, provided, or otherwise made accessible on or through the Services. You acknowledge that all Content accessed by you using the Services is at your own risk and you will be solely responsible for any damage or loss to you or any other party resulting therefrom. We do not guarantee that any Content you access on or through the Services is or will continue to be accurate.</p>
                    <br />
                    <h1 className='font-bold'>6. AVAILABILITY OF CONTENT</h1>
                    <p>We do not guarantee that any Content will be made available on the Site or through the Services. We reserve the right to, but do not have any obligation to, (i) remove, edit or modify any Content in our sole discretion, at any time, without notice to you and for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content or if we are concerned that you may have violated these Terms of Use), or for no reason at all and (ii) to remove or block any Content from the Services.</p>
                    <br />
                    <h1 className='font-bold'>7. RULES OF CONDUCT</h1>
                    <p>As a condition of use, you promise not to use the Services for any purpose that is prohibited by these Terms of Use. You are responsible for all of your activity in connection with the Services. You shall not:

                        (i) take any action that imposes or may impose (as determined by us in our sole discretion) an unreasonable or disproportionately large load on our (or our third party providers’) infrastructure;
                        (ii) interfere or attempt to interfere with the proper working of the Services or any activities conducted on the Services;
                        (iii) bypass, circumvent or attempt to bypass or circumvent any measures we may use to prevent or restrict access to the Services (or other accounts, computer systems or networks connected to the Services);
                        (iv) run any form of auto-responder or “spam” on the Services;
                        (v) use manual or automated software, devices, or other processes to “crawl” or “spider” any page of the Site;
                        (vi) harvest or scrape any Content from the Services;
                        (vii) distribute information you know is false, misleading, untruthful, unlawful, or inaccurate,
                        (viii) upload any software viruses or any other computer codes, files, or programs that are designed or intended to disrupt, damage, limit or interfere with the proper function of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any system, data, password or other information of ours or of any third party; or
                        (ix) otherwise take any action in violation of our guidelines and policies.</p>
                    <br />
                    <p>You shall not (directly or indirectly):

                        (i) decipher, decompile, disassemble, reverse engineer or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Services (including without limitation any application), except to the limited extent applicable laws specifically prohibit such restriction,
                        (ii) modify, translate, or otherwise create derivative works of any part of the Services, or
                        (iii) copy, rent, lease, distribute, or otherwise transfer any of the rights that you receive hereunder. You shall abide by all applicable local, state, national and international laws and regulations.</p>
                    <br />
                    <p>We also reserve the right to access, read, preserve, and disclose any information as we reasonably believe is necessary to

                        (i) satisfy any applicable law, regulation, legal process or governmental request,
                        (ii) enforce these Terms of Use, including investigation of potential violations hereof,
                        (iii) detect, prevent, or otherwise address fraud, security or technical issues,
                        (iv) respond to user support requests, or
                        (v) protect the rights, property or safety of us, our users and the public.</p>

                    <h1 className='font-bold'>9. THIRD PARTY SERVICES</h1>
                    <p>The Services may permit you to link to other websites, services or resources on the Internet, and other websites, services or resources may contain links to the Services. When you access third party resources on the Internet, you do so at your own risk. These other resources are not under our control, and you acknowledge that we are not responsible or liable for the content, functions, accuracy, legality, appropriateness or any other aspect of such websites or resources. The inclusion of any such link does not imply our endorsement or any association between us and their operators. You further acknowledge and agree that we shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such website or resource.</p>
                    <br />
                    <h1 className='font-bold'>10. PAYMENT METHOD</h1>
                    <p>10.1. The Site currently uses third parties to process payments. Our third-party payment processors accept payments through various credit cards, including Visa, MasterCard, American Express and Discover, as detailed on the applicable payment screen.</p>
                    <p>10.2. The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer or other provider of your chosen Payment Method. If we, through the Payment Processor, do not receive payment from you, you agree to pay all amounts due on your Billing Account upon demand.</p>
                    <br />
                    <h1 className='font-bold'>11. SHIPPING</h1>
                    <p>11.1. Certain of our Services may involve the purchase of products offered by us that would be shipped to an address provided by you.</p>
                    <p>11.2. All purchases of physical items from Stratuscent are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to you upon our delivery to the carrier.</p>
                    <p>11.3. We will not be responsible for any shipping delays or loss of product beyond our control, including any delays created by products being held at border customs en route to a customer’s shipment address.</p>
                    <br />
                    <h1 className='font-bold'>12. WARRANTY DISCLAIMER</h1>
                    <p>12.1. We have no special relationship with or fiduciary duty to you. You acknowledge that we have no duty to take any action regarding: which users gain access to the Services; what Content you access via the Services; or how you may interpret or use the Content. You release us from all liability for you having acquired or not acquired Content through the Services. We make no representations concerning any Content contained in or accessed through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, or legality of material or Content contained in or accessed through the Services.</p>
                    <p>12.2. THE SERVICES AND STRATUSCENT’S OR OUR LICENSORS’ INTELLECTUAL PROPERTY ARE PROVIDED “AS IS”, “AS AVAILABLE” AND WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. WE, AND OUR DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, PARTNERS AND CONTENT PROVIDERS DO NOT WARRANT THAT:

                        (I) THE SERVICES WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION;
                        (II) ANY DEFECTS OR ERRORS WILL BE CORRECTED;
                        (III) ANY CONTENT OR SOFTWARE AVAILABLE AT OR THROUGH THE SERVICES IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR
                        (IV) THE RESULTS OF USING THE SERVICES WILL MEET YOUR REQUIREMENTS. YOUR USE OF THE SERVICES IS SOLELY AT YOUR OWN RISK.</p>
                    <br />
                    <h1 className='font-bold'>  13. INDEMNIFICATION</h1>
                    <p>You shall defend, indemnify, and hold harmless us, our affiliates and each of our and their respective employees, contractors, directors, suppliers and representatives from all liabilities, claims, and expenses, including reasonable attorneys’ fees, that arise from or relate to your use or misuse of, or access to, the Services or Content in violation of these Terms of Use, or infringement by you, or any third party using your Account or identity in the Services, of any intellectual property or other right of any person or entity. We reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will assist and cooperate with us in asserting any available defenses.</p>
                    <br />
                    <h1 className='font-bold'>14. LIMITATION OF LIABILITY</h1>
                    <p>14.1. NEITHER STRATUSCENT NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING NOZE, INCLUDING OUR LICENSORS, WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE STRATUSCENT’S OR OUR LICENSORS’ INTELLECTUAL PROPERTY, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT STRATUSCENT HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
                    <br />
                    <p>14.2. IN NO EVENT WILL STRATUSCENT’S TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE NOZE OR TO ACCESS YOUR CONTENT EXCEED THE AMOUNTS YOU HAVE PAID TO STRATUSCENT FOR USE OF NOZE OR TWO HUNDRED DOLLARS ($200), IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO STRATUSCENT, AS APPLICABLE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN STRATUSCENT AND YOU</p>
                    <br />
                    <h1 className='font-bold'>15. GOVERNING LAW AND JURISDICTION</h1>
                    <p>These Terms of Use shall be governed by and construed in accordance with the laws of the Province of Quebec, including its conflicts of law rules, and Canada. You agree that any dispute arising from or relating to the subject matter of these Terms of Use shall be governed by the exclusive jurisdiction and venue of the state and Federal courts of Queb</p>
                    <br />
                    <h1 className='font-bold'>16. MODIFICATION</h1>
                    <p>We reserve the right, in our sole discretion, to modify or replace any of these Terms of Use, or change, suspend, or discontinue the Services (including without limitation, the availability of any feature, database, or content) at any time by posting a notice on the Site or by sending you notice through the Services, via e-mail or by another appropriate means of electronic communication. We may also impose limits on certain features and services or restrict your access to parts or all of the Services without notice or liability. While we will timely provide notice of modifications, it is also your responsibility to check these Terms of Use periodically for changes. Your continued use of the Services following notification of any changes to these Terms of Use constitutes acceptance of those changes.</p>
                    <br />
                    <h1 className='font-bold'>17. MISCELLANEOUS ENTIRE AGREEMENT AND SEVERABILITY</h1>
                    <p>These Terms of Use constitute the entire agreement between you and us with respect to the Device and the Services, including use of the Website and App, and supersede all prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and us with respect to the Services. If any provision of these Terms of Use is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that these Terms of Use will otherwise remain in full force and effect and enforceable. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.</p>
                    <br />
                    <h1 className='font-bold'>18. FORCE MAJEURE</h1>
                    <p>We shall not be liable for any failure to perform our obligations hereunder where such failure results from any cause beyond our reasonable control, including, without limitation, mechanical, electronic or communications failure or degradation.</p>
                    <br />
                    <h1 className='font-bold'>19. ASSIGNMENT</h1>
                    <p>These Terms of Use are personal to you, and are not assignable, transferable or sublicensable by you except with our prior written consent. We may assign, transfer or delegate any of our rights and obligations hereunder without consent.</p>
                    <br />
                    <h1 className='font-bold'>20. NOTICEST</h1>
                    <p>Unless otherwise specified in these Terms of Service, all notices under these Terms of Use including those regarding modifications to these Terms, will be given: (i) by Stratuscent via email; or (ii) by posting to our website. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</p>
                    <br />
                    <h1 className='font-bold'>21. NO WAIVER</h1>
                    <p>Our failure to enforce any part of these Terms of Use shall not constitute a waiver of our right to later enforce that or any other part of these Terms of Use. Waiver of compliance in any particular instance does not mean that we will waive compliance in the future. Any waiver of compliance with these Terms of Use will be effective only if in writing and signed by a duly authorized representative of Stratuscent.</p>
                    <br />
                    <h1 className='font-bold'>22. HEADINGS</h1>
                    <p>The section and paragraph headings in these Terms of Use are for convenience only and shall not affect their interpretation .</p>
                    <br />
                    <h1 className='font-bold'>23. DISPUTE RESOLUTION</h1>
                    <p>23.1. You and Stratuscent agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of Noze (collectively, “Disputes”) will be settled by binding arbitration, except that each party retains the right:

                        (i) to bring an individual action in small claims court and
                        (ii) to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party’s copyrights, trademarks, trade secrets, patents or other intellectual property rights (the action described in the foregoing clause (ii), an “IP Protection Action”).

                        The exclusive jurisdiction and venue of any IP Protection Action will be the provincial and federal courts located in Canada and each of the parties hereto waives any objection to jurisdiction and venue in such courts. You acknowledge and agree that you and Stratuscent are each waiving the right to a trial by jury or to participate as a plaintiff or class member in any purported class action or representative proceeding. Further, unless both you and Stratuscent otherwise agree in writing, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of any class or representative proceeding.</p>
                    <p>23.2. If Stratuscent changes this “Dispute Resolution” section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending us written notice (including by email to help@getnoze.com) within 30 days of the date such change became effective, as indicated in the “Last Updated” date above or in the date of Stratuscent’s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any dispute between you and Stratuscent in accordance with the provisions of this “Dispute Resolution” section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).

                        MANDATORY ARBITRATION AND CLASS ACTION WAIVER FOR RESIDENTS OF THE UNITED STATES. PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.</p>
                    <p>24.1.Application You and Stratuscent agree that these Terms affect interstate commerce and that the U.S. Federal Arbitration Act governs the interpretation and enforcement of these arbitration provisions. This section entitled “Mandatory Arbitration and Class Action Waiver for Residents of the United States” is intended to be interpreted broadly and governs any and all disputes between you and Stratuscent. Any and all disputes may include, but are not limited to

                        (i) claims arising out of or relating to any aspect of the relationship between you and Stratuscent, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory;
                        (ii) claims that arose before these Terms or any prior agreement (including, but not limited to, claims related to advertising); and
                        (iii) claims that may arise after the termination of these Terms. The only disputes excluded from the broad prohibition in this subsection entitled “Application” are the litigation of certain intellectual property and small court claims, as provided in the subsection entitled “Exception” below.</p>
                    <p>24.2. Initial Dispute Resolution Most disputes can be resolved without resorting to arbitration. If you have any dispute with us, you agree that you will try to resolve your dispute directly with us before taking any formal action, by contacting us at the address or email address set forth below. When you contact us, you must provide a brief, written description of the dispute and your contact information. If you have an account with us, you must include the email address associated with your account. Except for intellectual property and small claims court claims (see the subsection entitled “Exception” below), you and Stratuscent agree to use good faith efforts to resolve any dispute, claim, question, or disagreement directly through consultation with each other. You and Stratuscent agree to engage in good faith discussions before initiating a lawsuit or arbitration and understand those good faith discussions are a precondition of initiating a lawsuit or arbitration.</p>
                    <p>24.3. Binding Arbitration If the parties do not reach an agreed-upon solution within a period of sixty (60) days from the time informal dispute resolution is initiated under the Initial Dispute Resolution provision above, then either party may initiate binding arbitration as the sole means to resolve claims (except as provided in the subsection entitled “Exception” below), as long as the party agrees with the terms set forth below. Specifically, all claims arising out of or relating to these Terms (including the Terms’ formation, performance, and breach), the parties’ relationship with each other, and/or your use of Noze shall be finally settled by binding arbitration administered by JAMS in accordance with either (i) the JAMS Streamlined Arbitration Procedure Rules, for claims that do not exceed $250,000; or (ii) the JAMS Comprehensive Arbitration Rules and Procedures, for claims exceeding $250,000. The JAMS rules and procedures just identified shall be those effect at the time the arbitration is initiated (not the Last Modified date of these Terms), excluding any rules or procedures governing or permitting class actions.</p>
                    <p>24.4. Arbitrator’s Powers The arbitrator (and not any federal, state, or local court or agency) shall have exclusive authority to resolve all disputes arising out of or relating to the interpretation, applicability, enforceability, or formation of these Terms. Such disputes may include, but are not limited to, any claim that all or any part of these Terms is void or voidable, whether a claim is subject to arbitration, or the question of waiver by litigation conduct. The arbitrator shall be empowered to grant whatever relief would be available in a court under law or in equity. The arbitrator’s award shall be written and shall be binding on the parties and may be entered as a judgment in any court of competent jurisdiction.</p>
                    <p>24.5. Class Action Waiver YOU AND STRATUSCENT AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. This means that you and Stratuscent expressly waive any rights to file a class action or seek relief on a class basis. If any court or arbitrator determines that the class action waiver set forth in this paragraph is void or unenforceable for any reason or that an arbitration can proceed on a class basis, then the arbitration provisions set forth above shall be deemed null and void in their entirety and the parties shall be deemed to have not agreed to arbitrate disputes.</p>
                    <p>24.6. Exception Litigation of Intellectual Property and Small Claims Court Claims. Notwithstanding the parties’ agreement to resolve all disputes through arbitration, either party may bring enforcement actions, validity determinations or claims arising from or relating to theft, piracy, or unauthorized use of intellectual property in state or federal court with jurisdiction or in the U.S. Patent and Trademark Office to protect its intellectual property rights. “Intellectual property rights” means patents, copyrights, moral rights, trademarks, and trade secrets, but does not include privacy or publicity rights. Either party may also seek relief in a small claims court for disputes or claims within the scope of that court’s jurisdiction.

                    </p>
                    <p>24.7. 30-Day Right to Opt Out You have the right to opt out and not be bound by the arbitration and class action waiver provisions set forth above by sending written notice of your decision to opt out to Stratuscent Inc., 7171 Rue Frederick Banting, Montréal, QC H4S 1Z9 Attn: Legal Counsel. Your written notice must have the subject line, “ARBITRATION AND CLASS ACTION WAIVER OPT-OUT.” The notice must be sent within thirty (30) days of (i) July 15, 2021; or (ii) your first date that you used the Site that contained any versions of the Terms that included this version of the Mandatory Arbitration and Class Action Waiver, whichever is later. Otherwise you shall be bound to arbitrate disputes in accordance with this section entitled “Mandatory Arbitration and Class Action Waiver for Residents of the United States”. If you opt out of these arbitration provisions, Stratuscent also will not be bound by them.

                    </p>
                    <p>24.8. Changes to This Section Stratuscent will provide thirty (30) days’ notice of any material changes to this section by posting notice on the Site or informing you via email, and complying with any other applicable legal notice or consent requirements. Amendments will become effective thirty (30) days after they are posted on the Site or sent to you by email. Changes to this section will otherwise apply prospectively only to claims arising after the thirtieth (30th) day.

                        If a court or arbitrator decides that this subsection (“Changes to this Section”) is not enforceable or valid, then this subsection will be deemed to be severed from the section entitled “Mandatory Arbitration and Class Action Waiver.” If this happens, the court or arbitrator shall apply the first Mandatory Arbitration and Class Action Waiver section or similar section in existence after you began using the Site.    </p>
                    <p>24.9. Survival This Mandatory Arbitration and Class Action Waiver section shall survive any termination of your use of the Site.</p>
                    <br />
                    <h1 className='mt-5 font-bold'>25. NO SUPPORT</h1>
                    <p>We are under no obligation to provide support for the Services. In instances where we may offer support, the support will be subject to published policies.</p>
                    <p className='mt-5'>Last Updated: <span className='font-bold '> July 15, 2021</span></p>
                </div>
            </div>
        </div>
    );
};

export default Terms;